# Generated by Django 4.2.1 on 2023-07-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('author', models.TextField(default='')),
                ('year', models.TextField(default='')),
                ('link', models.TextField(default='http://127.0.0.1:8000/')),
                ('img', models.TextField(default='')),
            ],
        ),
    ]
