# Generated by Django 4.2.1 on 2023-07-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='year',
            field=models.IntegerField(max_length=3),
        ),
    ]
