# Generated by Django 4.2.1 on 2023-07-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_news_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='activity_descrption',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.TextField(default=''),
        ),
    ]
