# Generated by Django 4.2.1 on 2023-07-25 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_news_activity_descrption_news_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='activity_descrption',
            new_name='activity_description',
        ),
    ]
