# Generated by Django 4.2.1 on 2023-07-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_rename_activity_descrption_news_activity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='insta_link',
            field=models.TextField(default='https://www.instagram.com/ecops_ewha/'),
        ),
    ]
