# Generated by Django 4.2.1 on 2023-07-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(max_length=3)),
                ('img', models.ImageField(upload_to='')),
                ('program_name', models.CharField(max_length=100)),
            ],
        ),
    ]
