# Generated by Django 4.2.1 on 2023-07-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenger',
            name='insta_link',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='challenger',
            name='program_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='challenger',
            name='img',
            field=models.ImageField(upload_to='challenger/'),
        ),
        migrations.AlterField(
            model_name='challenger',
            name='year',
            field=models.IntegerField(),
        ),
    ]
