# Generated by Django 4.2.1 on 2023-07-23 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenger', '0003_alter_challenger_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenger',
            name='img',
        ),
        migrations.RemoveField(
            model_name='challenger',
            name='year',
        ),
    ]
