# Generated by Django 4.2.1 on 2023-07-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenger', '0004_remove_challenger_img_remove_challenger_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenger',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/challenger/'),
        ),
        migrations.AddField(
            model_name='challenger',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenger',
            name='insta_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenger',
            name='program_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenger',
            name='program_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
