# Generated by Django 4.2.1 on 2023-07-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenger', '0005_challenger_img_challenger_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenger',
            name='year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
