# Generated by Django 4.2.1 on 2023-07-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenger', '0006_alter_challenger_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenger',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
    ]
