# Generated by Django 4.2.1 on 2023-07-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenger', '0008_alter_challenger_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenger',
            name='track',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
