# Generated by Django 4.2.1 on 2023-07-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='std_id',
            field=models.IntegerField(default=2271092),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='members',
            name='img',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
